config/routes.rb
Rails.application.routes.draw do

  get    'about',                 to: 'home#about'
  get    'contact',               to: 'home#contact'
  get    '/signup',               to: 'users#new'
  post   '/signup',               to: 'users#create'
  get    '/login',                to: 'sessions#new'
  post   '/login',                to: 'sessions#create'
  delete '/logout',               to: 'sessions#destroy'

  
  # TOP
  root 'home#top'
  
  # 管理者
  namespace :admin do
    
    # 管理者TOP
    root 'home#index'
    
    # ユーザー管理
    resources :users
    
    # 商品管理
    resources :products
    
    # カテゴリ管理
    resources :categories, except: [:show]
    
    # 購入者情報
    resources :purchasers, except: [:new, :create]
    
    # 注文商品
    resources :ordered_items, only: [:show, :update, :destroy]

    # お問い合わせ
    resources :contacts, only: [:index, :show]
    
  end
  
  namespace :front do

    # お問い合わせ
    resources :contacts, only: [:new, :create]
    
  end
  
  resources :users, except: [:index, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :products, only: [:index, :show]
  resources :cart_items

  get    'procedures/login_form',      to: 'procedures#login_form'
  get    'procedures/new',             to: 'procedures#new'
  get    'procedures/entry_form',      to: 'procedures#entry_form'
  get    'procedures/nonmember_form',  to: 'procedures#nonmember_form'
  post   'procedures/entry',           to: 'procedures#entry'
  patch  'procedures/entry',           to: 'procedures#entry'
  post   'procedures/create',          to: 'procedures#create'
  post   'procedures/purchase',        to: 'procedures#purchase'
  get    'procedures/confirmation',    to: 'procedures#confirmation'
  get    'procedures/select_method',   to: 'procedures#select_method'
  patch  'procedures/decide_method',   to: 'procedures#decide_method'
  post   'procedures/payment',         to: 'procedures#payment'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
# == Schema Information
#
# Table name: cart_items
#
#  id         :bigint           not null, primary key
#  product_id :bigint
#  cart_id    :bigint
#  quantity   :integer          default(0)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CartItem < ApplicationRecord

  belongs_to :product
  belongs_to :cart
  validates :quantity, numericality: {greater_than_or_equal_to: 0}
  
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :setup_cart_item, only: [:index, :create, :destroy]

  def index
  end

  def create
    @cart_item.update cart_item_params
    redirect_to cart_items_path, flash: {success: 'カートに商品を追加しました'}
  end

  def update
    cart_item = current_cart.cart_items.find_or_initialize_by(id: params[:id])
    cart_item_params[:quantity].to_i != 0 ? cart_item.update!(cart_item_params) : cart_item.destroy
    redirect_to cart_items_path, flash: {success: 'カート内の商品を更新しました'}
  end

  def destroy
    @cart_item.destroy!
    redirect_to cart_items_path, flash: {success: 'カートから商品を取り出しました'}
  end

  private

    def cart_item_params
      params.require(:cart_item).permit(:quantity, :product_stock_id)
    end
end

app/views/cart_items/index.html.slim
- provide :title, 'ショッピングカート'
.p-cart
  .p-cart__inner
    .p-cart__body
      h1.p-cart__heading ショッピングカート
      .p-cart__notice
        - if current_cart.cart_items.empty?
          p カート内に商品はありません
      table.p-cart__cart
        - current_cart.cart_items.each do |cart_item|
          tr.p-cart__table
            td.p-cart__image
              = link_to product_path(cart_item.stock.product_id) do
                - if cart_item.stock.product.image.attached?
                  = image_tag cart_item.stock.product.thumbnail, alt: 'no_image', width: '100%'
                - else 
                  = image_tag 'no_image.png', width: '100%'
            td.p-cart__name
              = link_to product_path(cart_item.stock.product_id) do
                p = cart_item.stock.product.name
              .p-cart__delete_btn
                = link_to '削除', cart_item_path(cart_item.stock.id), method: :delete, class: 'p-cart__btn' , data: { confirm: 'カートから取り出しますか？' }
            td.p-cart__size
              p = cart_item.stock.size.upcase
            td.p-cart__form
              .p-cart__form_inner
                = form_with model: cart_item, url: cart_item_path(cart_item.id), local: true do |f|
                  .p-cart__form_item
                    = f.label :quantity, '数量'
                    = f.number_field :quantity, class: 'p-cart__quantity', min: 0
                  .p-cart__update = f.submit '更新', class: "p-cart__update_button"
                  td.p-cart__price
                    p = "#{(cart_item.quantity * cart_item.stock.product.price).to_s(:delimited)}円"
      .p-cart__subtotal
        - if current_cart.cart_items.present?
          p = "合計金額: #{current_cart.total_price.to_s(:delimited)}円"
    .p-cart__menu
      = link_to "<<買い物を続ける", products_path, class: 'p-cart__previous'
      - if current_cart.cart_items.present?
        = link_to '購入手続きに進む>>>>', logged_in?? procedures_entry_form_path : procedures_login_form_path, class: 'p-cart__next'