config/routes.rb
Rails.application.routes.draw do

  get    'about',                 to: 'home#about'
  get    'contact',               to: 'home#contact'
  get    '/signup',               to: 'users#new'
  post   '/signup',               to: 'users#create'
  get    '/login',                to: 'sessions#new'
  post   '/login',                to: 'sessions#create'
  delete '/logout',               to: 'sessions#destroy'

  
  # TOP
  root 'home#top'
  
  # 管理者
  namespace :admin do
    
    # 管理者TOP
    root 'home#index'
    
    # ユーザー管理
    resources :users
    
    # 商品管理
    resources :products
    
    # カテゴリ管理
    resources :categories, except: [:show]
    
    # 購入者情報
    resources :purchasers, except: [:new, :create]
    
    # 注文商品
    resources :ordered_items, only: [:show, :update, :destroy]

    # お問い合わせ
    resources :contacts, only: [:index, :show]
    
  end
  
  namespace :front do

    # お問い合わせ
    resources :contacts, only: [:new, :create]
    
  end
  
  resources :users, except: [:index, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :products, only: [:index, :show]
  resources :cart_items

  get    'procedures/login_form',      to: 'procedures#login_form'
  get    'procedures/new',             to: 'procedures#new'
  get    'procedures/entry_form',      to: 'procedures#entry_form'
  get    'procedures/nonmember_form',  to: 'procedures#nonmember_form'
  post   'procedures/entry',           to: 'procedures#entry'
  patch  'procedures/entry',           to: 'procedures#entry'
  post   'procedures/create',          to: 'procedures#create'
  post   'procedures/purchase',        to: 'procedures#purchase'
  get    'procedures/confirmation',    to: 'procedures#confirmation'
  get    'procedures/select_method',   to: 'procedures#select_method'
  patch  'procedures/decide_method',   to: 'procedures#decide_method'
  post   'procedures/payment',         to: 'procedures#payment'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :bigint           not null, primary key
#  name        :string(255)
#  price       :integer
#  comment     :string(255)
#  category_id :integer
#  color       :string(255)
#  size        :integer          default(0)
#  stock       :integer          default(0)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ApplicationRecord

  #----------------------------------------
  #  ** Includes **
  #----------------------------------------

  #----------------------------------------
  #  ** Constants **
  #----------------------------------------

  #----------------------------------------
  #  ** Enums **
  #----------------------------------------

  #----------------------------------------
  #  ** Validations **
  #----------------------------------------

  validates :name,	 	presence: true, length: {maximum: 30}
  validates :price, 	presence: true
  validates :comment, presence: true, length: {maximum: 140}
  validates :image,   presence: true, allow_nil: true
  validates_numericality_of :price, message: 'が有効な数値ではありません'

  #----------------------------------------
  #  ** Associations **
  #----------------------------------------

  belongs_to :category, optional: true
  has_one_attached :image

  # 在庫
  has_many :stocks, class_name: 'ProductStock', dependent: :delete_all
  accepts_nested_attributes_for :stocks

  #----------------------------------------
  #  ** Delegates **
  #----------------------------------------

  #----------------------------------------
  #  ** Scopes **
  #----------------------------------------

  #----------------------------------------
  #  ** Methods **
  #----------------------------------------

  def thumbnail

    self.image.variant(combine_options: {resize: '640x640^', crop:'640x640+0+0',gravity: :center}).processed
  end

  # 在庫の合計数
  def total_stock

    self.stocks.pluck(:quantity).sum
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin

  def index
    @q = Product.ransack(params[:q])
    @categories = Category.all
    @products = @q.result(distinct: true).order('created_at DESC').paginate(page: params[:page]).per_page(20)
  end

  def new
    @product = Product.new
    @product.stocks.build([
      {size: :free},
      {size: :xs},
      {size: :s},
      {size: :m},
      {size: :l},
      {size: :xl},
    ])
  end

  def create
    @product = Product.new product_params
    if @product.save
      redirect_to admin_products_path, flash: {success: "商品「#{@product.name}」を登録しました"}
    else
      render :new
    end
  end

  def show
    @product = Product.find_by(id: params[:id])
  end

  def edit
  	@product = Product.find_by(id: params[:id])
  end

  def update
    @product = Product.find_by(id: params[:id])
    @product.update product_params
  	redirect_to admin_products_path, flash: {success: '商品情報を更新しました'}
  end

  def destroy
    @product = Product.find_by(id: params[:id])
  	@product.destroy
  	redirect_to admin_products_path, flash: {success: '出品を取りやめました'}
  end

  private
    def product_params
      params.require(:product).permit :name, :category_id, :price, :comment, :image, stocks_attributes: [:id, :color, :size, :quantity]
    end

    def search_params
      params.require(:q).permit(:name_cont)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :setup_cart_item, only: [:show]
  
  def index
    @q = Product.ransack(params[:q])
    @categories = Category.all
    @products = @q.result(distinct: true).reverse_order.paginate(page: params[:page]).per_page(20)
  end

  def show
    @product = Product.find params[:id]
  end

end

app/views/admin/products/_form.html.slim
= form_with model: [:admin, @product], local: true do |f|
  .form
    #js-product-stocks.form-body
      - @product.errors.full_messages.each do |message|
        .form-error
          = message
      
      .c-form-label = f.label :name, '品名'
      = f.text_field :name, placeholder: '品名', required: :true

      .c-form-label = f.label :category, 'カテゴリ'
      = f.collection_select :category_id, Category.all, :id, :name
      = link_to 'カテゴリ新規作成', new_admin_category_path

      .c-form-label = f.label :image, '画像'
        = f.file_field :image, accept: 'image/jpg,image/jpeg,image/png,image/gif'

      .c-form-label = f.label :price, '値段'
      = f.text_field :price, value: @product.price, required: :true
        |円

      .c-form-label = f.label :comment, 'コメント'
      = f.text_area :comment, placeholder: 'コメント', rows: 5, required: :true

      = f.fields_for :stocks do |stock|

        .c-form-label
          label = "サイズ: #{stock.object.size.upcase}"
        = stock.hidden_field :size

        .c-form-label = stock.label :quantity, '在庫数'
        = stock.number_field :quantity, min: 0
      
      .u-ta-center.u-mt-30 = f.submit '出品する'

app/views/admin/products/edit.html.slim
.main.products-new
  .container
    h1.form-heading 編集する
    = render 'form'

app/views/admin/products/index.html.slim
.p-stocks
  .p-stocks__inner
    h1.p-stocks__heading 在庫一覧
    = render 'products/search_form'
    .p-stocks__listWrapper
      table.p-stocks__list
        thead.p-stocks__thread
          tr.p-stocks__item
            th.p-stocks__header ID
            th.p-stocks__header イメージ
            th.p-stocks__header 商品名
            th.p-stocks__header カテゴリー
            th.p-stocks__header サイズ
            th.p-stocks__header 金額
            th.p-stocks__header
        tbody.p-stocks__body
          - @products.each do |product|
            tr.p-stocks__item
              td.p-stocks__data = product.id
              td.p-stocks__image
                = link_to edit_admin_product_path(product.id) do
                  - if product.image.attached?
                    = image_tag product.image, width: '100%'
                  - else 
                    = image_tag 'no_image.png', width: '100%'
              td.p-stocks__data = link_to product.name, edit_admin_product_path(product.id)
              td.p-stocks__data = product.category&.name
              td.p-stocks__data = product.size
              td.p-stocks__data = product.price.to_s(:delimited)
              td.p-stocks__data = link_to '編集', edit_admin_product_path(product.id)
              td.p-stocks__destroy = link_to '削除', admin_product_path(product.id), method: :delete, data: { confirm: "#{product.name}の出品を取りやめますか？" }, class: 'btn btn-danger'
    .pagination = will_paginate @products

app/views/admin/products/new.html.slim
.main-products-new
  .container
    h1.form-heading 出品
    p 商品情報を入力してください。
    = render 'form'