config/routes.rb
Rails.application.routes.draw do

  get    'about',                 to: 'home#about'
  get    'contact',               to: 'home#contact'
  get    '/signup',               to: 'users#new'
  post   '/signup',               to: 'users#create'
  get    '/login',                to: 'sessions#new'
  post   '/login',                to: 'sessions#create'
  delete '/logout',               to: 'sessions#destroy'

  
  # TOP
  root 'home#top'
  
  # 管理者
  namespace :admin do
    
    # 管理者TOP
    root 'home#index'
    
    # ユーザー管理
    resources :users
    
    # 商品管理
    resources :products
    
    # カテゴリ管理
    resources :categories, except: [:show]
    
    # 購入者情報
    resources :purchasers, except: [:new, :create]
    
    # 注文商品
    resources :ordered_items, only: [:show, :update, :destroy]

    # お問い合わせ
    resources :contacts, only: [:index, :show]
    
  end
  
  namespace :front do

    # お問い合わせ
    resources :contacts, only: [:new, :create]
    
  end
  
  resources :users, except: [:index, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :products, only: [:index, :show]
  resources :cart_items

  get    'procedures/login_form',      to: 'procedures#login_form'
  get    'procedures/new',             to: 'procedures#new'
  get    'procedures/entry_form',      to: 'procedures#entry_form'
  get    'procedures/nonmember_form',  to: 'procedures#nonmember_form'
  post   'procedures/entry',           to: 'procedures#entry'
  patch  'procedures/entry',           to: 'procedures#entry'
  post   'procedures/create',          to: 'procedures#create'
  post   'procedures/purchase',        to: 'procedures#purchase'
  get    'procedures/confirmation',    to: 'procedures#confirmation'
  get    'procedures/select_method',   to: 'procedures#select_method'
  patch  'procedures/decide_method',   to: 'procedures#decide_method'
  post   'procedures/payment',         to: 'procedures#payment'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  require 'payjp'
	before_action :authenticate_cart
  before_action :authenticate_method, only: [:confirmation, :purchase]
  before_action :logged_in_user, only: [:entry_form]
  before_action :forbid_login_user, only: [:new, :create, :login_form, :nonmember_form]
  
  #購入者専用のログイン画面
  def login_form
  end

  def logged_in_user
    unless logged_in?
      store_location
  		redirect_to procedures_login_form_path
  	end
  end

  #購入者専用の新規登録画面
  def new
  	@user = User.new
  end

  #購入者情報の入力
  def entry_form
    @purchaser = Purchaser.find_or_initialize_by(user_id: @current_user&.id)
  end

  def nonmember_form
    @purchaser = Purchaser.find_or_initialize_by(id: session[:guest_id])
  end

  #購入者情報の確定
  def entry
    if logged_in? && @purchaser = Purchaser.find_or_create_by(user_id: @current_user&.id)
      @purchaser.update! purchaser_params
    elsif @purchaser = Purchaser.find_by(id: session[:guest_id])
      @purchaser.update! purchaser_params
    else
      @purchaser = Purchaser.create! purchaser_params
      session[:guest_id] = @purchaser.id
    end
    redirect_to procedures_select_method_path
  rescue
    render :entry_form
  end

  #支払い方法選択
  def select_method
  end

  #支払い方法の確定
  def decide_method
    if cart_params
      current_cart.update cart_params
      redirect_to procedures_confirmation_path
    else
      flash[:danger] = 'お支払い方法を選択して下さい'
      redirect_to procedures_select_method_path
    end
  end

  #注文内容の確認
  def confirmation

    if @current_user.present?
      @purchaser = Purchaser.find_by(user_id: @current_user.id)
    else
      @purchaser = Purchaser.find_by(id: session[:guest_id])
    end
  end

  #注文確定
  def purchase

    if @current_user.present?
      @purchaser = Purchaser.find_by(user_id: @current_user.id)
    else 
      @purchaser = Purchaser.find_by(id: session[:guest_id])
    end 

    OrderedItem.transaction do
      ordered_items = []

      current_cart.cart_items.each do |cart_item|
        ordered_items << OrderedItem.new(
          quantity: cart_item.quantity,
          product_stock_id: cart_item.product_stock_id,
          purchaser_id: @purchaser.id,
          method: current_cart.method
        )

        cart_item.stock.quantity -= cart_item.quantity
        raise '商品の在庫が不足しています' if cart_item.stock.quantity < 0
        cart_item.stock.save!
      end

      OrderedItem.import! ordered_items

      if current_cart.method == 1
         Payjp.api_key = ENV['PAYJP_SECRET_KEY']
         Payjp::Charge.create(currency: 'jpy', amount: current_cart.total_price, card: params['payjp-token'])
      end

      current_cart.cart_items.delete_all
      current_cart.update(method: nil)
    end
    PurchaserMailer.purchaser_email(@purchaser).deliver_now
    PurchaserMailer.order_notification.deliver_now

    redirect_to products_path, flash: {success: 'お買い上げありがとうございます!'}
  rescue => e
    render plain: e.message
  end

  private

    def purchaser_params
      params.require(:purchaser).permit(:kana, :last_name, :first_name, :postal_code, :prefecture, :city, :address, :phone_number, :email, :email_confirmation, :user_id)
    end
    
    def cart_params
      params.require(:cart).permit(:method)
    end

end

app/views/procedures/_entry_form.html.slim
- provide :title, 'お客様情報入力'
.p-procedure
  .p-procedure__inner
    .p-procedure__heading お客様情報の入力
    = form_with model: @purchaser, url: procedures_entry_path, local: true do |f|
      = render 'shared/error_messages', object: f.object

      h3 お名前

      = f.label :kana, 'フリガナ'
      = f.text_field :kana, class: 'form-control', value: @purchaser.kana

      = f.label :last_name, '姓'
      = f.text_field :last_name, class: 'form-control', value: @purchaser.last_name

      = f.label :first_name, '名'
      = f.text_field :first_name, class: 'form-control', value: @purchaser.first_name
      
      h3 ご住所(お届け先)

      = f.label :postal_code, '郵便番号(ハイフン不要)'
      = f.text_field :postal_code, class: 'form-control', value: @purchaser.postal_code

      = f.label :prefecture, '都道府県'
      = f.text_field :prefecture, class: 'form-control', value: @purchaser.prefecture

      = f.label :city, '市区町村'
      = f.text_field :city, class: 'form-control', value: @purchaser.city

      = f.label :address, '番地以降'
      = f.text_field :address, class: 'form-control', value: @purchaser.address

      h3 ご連絡先

      = f.label :phone_number, '電話番号'
      = f.text_field :phone_number, class: 'form-control', value: @purchaser.phone_number

      = f.label :email, 'メールアドレス'
      = f.email_field :email, class: 'form-control', value: @purchaser.email

      = f.label :email_confirmation, 'メールアドレス(確認のため再度入力して下さい)'
      = f.email_field :email_confirmation, class: 'form-control', value: @purchaser.email

      = f.submit '次に進む>>', class: 'btn btn-primary'

app/views/procedures/confirmation.html.slim
- provide :title, 'ご注文確認'
.p-procedure
  .p-procedure__inner
    h1.p-procedure__heading ご注文内容の確認
    .p-procedure__notice
      p 下記ご注文内容をご確認下さい。
      - if current_cart.method == 'credit'
        p よろしければ「注文を確定し、カード情報を入力」ボタンを押して下さい。
      - else
        p よろしければ「注文を確定する」ボタンを押して下さい。

    .p-procedure__body
      .p-procedure__purchaser
        h3 お名前
        p
          | フリガナ:
          = @purchaser.kana
        p
          | 氏名:
          = @purchaser.last_name
          = @purchaser.first_name
        h3 ご住所(お届け先)
        p
          | 〒
          = @purchaser.postal_code
        p
          = @purchaser.prefecture
          = @purchaser.city
          = @purchaser.address
        h3 ご連絡先
        p
          | 電話番号:
          = @purchaser.phone_number
        p
          | メールアドレス:
          = @purchaser.email
      table.p-procedure__cart
        - current_cart.cart_items.each do |cart_item|
          tr.p-procedure__table
            td.p-procedure__image
              - if cart_item.stock.product.image.attached?
                = image_tag cart_item.stock.product.thumbnail, alt: 'no_image', width: '100%'
              - else 
                = image_tag 'no_image.png', width: '100%'
            td.p-procedure__name
              p = cart_item.stock.product.name
            td.p-procedure__form
              .p-procedure__form_inner
                - if cart_item.quantity >= 1
                  .p-procedure__form_item
                    p
                      |  × 
                      = cart_item.quantity
            td.p-procedure__subtotal
              p = "#{(cart_item.stock.product.price * cart_item.quantity).to_s(:delimited)}円"
    .p-procedure__total
      p.p-procedure__totalprice = "合計金額: #{current_cart.total_price.to_s(:delimited)}円"
    .p-procedure__menu
      .p-procedure__submit_button 
      - if current_cart.method == 'credit'
        = form_tag(action: :purchase, method: :post) do
          form[action='/pay' method='post']

            = javascript_include_tag 'https://checkout.pay.jp/', class: 'payjp-button', 'data-key': ENV['PAYJP_PUBLIC_KEY'], 'data-text': '注文を確定し、カード情報を入力', 'data-submit-text': '確定'

      - else
        =  link_to '注文を確定する', '/procedures/purchase', method: :post, class: 'p-procedure__COD', data: { confirm: '注文を確定します。'}

app/views/procedures/entry_form.html.slim
= render 'entry_form'

app/views/procedures/login_form.html.slim
- provide(:title, "ログイン")
- provide(:link, procedures_new_path)
- provide(:value, '1')
- provide(:button, 'ログインして購入手続きへ進む>>')
.p-procedure
  .p-procedure__inner
    h1.p-procedure__heading ログインして購入
    = render 'sessions/login_form'
    .p-procedure__next
      = link_to("ログインせずに購入手続きへ進む>>","/procedures/nonmember_form", class: 'p-procedure__nextButton')

app/views/procedures/new.html.slim
- provide(:title, "新規登録")
- provide(:page, '1')
- provide(:button_text, '新規登録して購入手続きへ進む')
.p-procedure
  .p-procedure__inner
    h1.p-procedure__heading 新規登録
    = render 'users/form'

app/views/procedures/nonmember_form.html.slim
= render 'entry_form'

app/views/procedures/select_method.html.slim
- provide :title, '支払方法選択'
.p-procedure
  .p-procedure__inner
    h1.p-procedure__heading お支払い方法の選択
    .p-procedure__form
      = form_with model: current_cart, url: procedures_decide_method_path, local: true do |f|
        = f.collection_radio_buttons :method, Cart.methods_i18n, :first, :last, include_hidden: false do |i|
          - content_tag(:div, class: 'p-procedures__form_item') do
            - i.radio_button(class: 'p-procedures__radio') + i.label(class: 'p-procedures__label')

        = f.submit '確認画面へ>>', class: 'btn btn-primary'