config/routes.rb
Rails.application.routes.draw do

  get    'about',                 to: 'home#about'
  get    'contact',               to: 'home#contact'
  get    '/signup',               to: 'users#new'
  post   '/signup',               to: 'users#create'
  get    '/login',                to: 'sessions#new'
  post   '/login',                to: 'sessions#create'
  delete '/logout',               to: 'sessions#destroy'

  
  # TOP
  root 'home#top'
  
  # 管理者
  namespace :admin do
    
    # 管理者TOP
    root 'home#index'
    
    # ユーザー管理
    resources :users
    
    # 商品管理
    resources :products
    
    # カテゴリ管理
    resources :categories, except: [:show]
    
    # 購入者情報
    resources :purchasers, except: [:new, :create]
    
    # 注文商品
    resources :ordered_items, only: [:show, :update, :destroy]

    # お問い合わせ
    resources :contacts, only: [:index, :show]
    
  end
  
  namespace :front do

    # お問い合わせ
    resources :contacts, only: [:new, :create]
    
  end
  
  resources :users, except: [:index, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :products, only: [:index, :show]
  resources :cart_items

  get    'procedures/login_form',      to: 'procedures#login_form'
  get    'procedures/new',             to: 'procedures#new'
  get    'procedures/entry_form',      to: 'procedures#entry_form'
  get    'procedures/nonmember_form',  to: 'procedures#nonmember_form'
  post   'procedures/entry',           to: 'procedures#entry'
  patch  'procedures/entry',           to: 'procedures#entry'
  post   'procedures/create',          to: 'procedures#create'
  post   'procedures/purchase',        to: 'procedures#purchase'
  get    'procedures/confirmation',    to: 'procedures#confirmation'
  get    'procedures/select_method',   to: 'procedures#select_method'
  patch  'procedures/decide_method',   to: 'procedures#decide_method'
  post   'procedures/payment',         to: 'procedures#payment'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :bigint           not null, primary key
#  name        :string(255)
#  price       :integer
#  comment     :string(255)
#  category_id :integer
#  color       :string(255)
#  size        :integer          default(0)
#  stock       :integer          default(0)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ApplicationRecord

  #----------------------------------------
  #  ** Includes **
  #----------------------------------------

  #----------------------------------------
  #  ** Constants **
  #----------------------------------------

  #----------------------------------------
  #  ** Enums **
  #----------------------------------------

  #----------------------------------------
  #  ** Validations **
  #----------------------------------------

  validates :name,	 	presence: true, length: {maximum: 30}
  validates :price, 	presence: true
  validates :comment, presence: true, length: {maximum: 140}
  validates :image,   presence: true, allow_nil: true
  validates_numericality_of :price, message: 'が有効な数値ではありません'

  #----------------------------------------
  #  ** Associations **
  #----------------------------------------

  belongs_to :category, optional: true
  has_one_attached :image

  # 在庫
  has_many :stocks, class_name: 'ProductStock', dependent: :delete_all
  accepts_nested_attributes_for :stocks

  #----------------------------------------
  #  ** Delegates **
  #----------------------------------------

  #----------------------------------------
  #  ** Scopes **
  #----------------------------------------

  #----------------------------------------
  #  ** Methods **
  #----------------------------------------

  def thumbnail

    self.image.variant(combine_options: {resize: '640x640^', crop:'640x640+0+0',gravity: :center}).processed
  end

  # 在庫の合計数
  def total_stock

    self.stocks.pluck(:quantity).sum
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin

  def index
    @q = Product.ransack(params[:q])
    @categories = Category.all
    @products = @q.result(distinct: true).order('created_at DESC').paginate(page: params[:page]).per_page(20)
  end

  def new
    @product = Product.new
    @product.stocks.build([
      {size: :free},
      {size: :xs},
      {size: :s},
      {size: :m},
      {size: :l},
      {size: :xl},
    ])
  end

  def create
    @product = Product.new product_params
    if @product.save
      redirect_to admin_products_path, flash: {success: "商品「#{@product.name}」を登録しました"}
    else
      render :new
    end
  end

  def show
    @product = Product.find_by(id: params[:id])
  end

  def edit
  	@product = Product.find_by(id: params[:id])
  end

  def update
    @product = Product.find_by(id: params[:id])
    @product.update product_params
  	redirect_to admin_products_path, flash: {success: '商品情報を更新しました'}
  end

  def destroy
    @product = Product.find_by(id: params[:id])
  	@product.destroy
  	redirect_to admin_products_path, flash: {success: '出品を取りやめました'}
  end

  private
    def product_params
      params.require(:product).permit :name, :category_id, :price, :comment, :image, stocks_attributes: [:id, :color, :size, :quantity]
    end

    def search_params
      params.require(:q).permit(:name_cont)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :setup_cart_item, only: [:show]
  
  def index
    @q = Product.ransack(params[:q])
    @categories = Category.all
    @products = @q.result(distinct: true).reverse_order.paginate(page: params[:page]).per_page(20)
  end

  def show
    @product = Product.find params[:id]
  end

end

app/views/products/_information.html.slim
.p-product__section_half
  .p-product__information
    h1.p-product__name = @product.name
    p.p-product__price = "#{@product.price.to_s(:delimited)}円"
    p.p-product__comment = @product.comment
  hr
  .p-product__menu
    .p-product__notice
      - if @product.total_stock <= 0
        p.p-product__soldout 売り切れ
      - else
        p ご希望のサイズを選択して下さい。
        span ※在庫があるサイズのみ表示しています。

    - @product.stocks.each do |stock|
      - if stock.quantity > 0
        dl.p-product__clearfix
          dt.p-product__clearfix_term
            div.p-product__clearfix_img
              - if stock.product.image.attached?
                = image_tag stock.product.thumbnail, alt: 'no_image', width: '75%'
              - else 
                = image_tag 'no_image.png', width: '100%'
            span.p-product__clearfix_txt
          dd.p-product__clearfix_discription
            .p-product__clearfix_stock
              p
                = stock.size.upcase
                br
                = "残り#{stock.quantity}点"

            .p-product__input
              = form_with model: @cart_item, url: @cart_item.new_record? ? cart_items_path : cart_item_path(@cart_item.id), local: true do |f|
                = f.hidden_field :quantity, value: @cart_item.new_record? ? 1 : @cart_item.quantity + 1
                = f.hidden_field :product_stock_id, value: stock.id
                .p-product__submit
                  = f.submit 'カートに入れる', class: 'p-product__button'

app/views/products/_photo.html.slim
.p-product__section_half
  .p-product__photo
    - if @product.image.attached?
      = image_tag @product.thumbnail, alt: 'no_image', width: '100%'
    - else 
      = image_tag 'no_image.png', width: '100%'

app/views/products/_product.html.slim
.p-product
  .p-product__inner
    - @products.each do |product|
      .p-product__grid
        = link_to product_path(product.id), class: 'p-product__card' do
          .p-product__image_container
            - if product.image.attached?
              = image_tag product.thumbnail, alt: 'product'
            - else 
              = image_tag 'no_image.png', width: '100%'
          .p-product__info-card
            p.p-product__name-card = product.name
            p.p-product__price-card = "¥#{product.price}"

app/views/products/_search_form.html.slim
.p-search
  .p-search__inner
    = search_form_for @q, url: admin_products_path, class: 'p-search__form' do |f|
      .p-search__item
        = f.label :name_cont, '商品名で検索', class: 'p-search__label'
        = f.search_field :name_cont, placeholder: 'お探しの商品名', class: 'p-search__field'
      .p-search__item
        = f.label :category_id_eq, 'カテゴリで検索', class: 'p-search__label'
        = f.collection_select :category_id_eq, @categories, :id, :name, :include_blank => '指定なし', class: 'p-search__field'
      = f.submit '検索', class: 'p-search__button'

app/views/products/edit.html.slim
.main.products-new
  .container
    h1.form-heading
      | 編集する
    = form_with model: @product, url: product_path(@product.id), local: true do |f|
      .form
        .form-body
          - @product.errors.full_messages.each do |message|
            .form-error
              = message
          
          .c-form-label = f.label :name, '品名'
          = f.text_field :name, placeholder: '品名', value: @product.name, required: :true

          .c-form-label = f.label :category, 'カテゴリー'
          = f.text_field :category, placeholder: 'カテゴリー'

          .c-form-label = f.label :price, '値段'
          = f.text_field :price, value: @product.price, required: :true
            |円

          p
            | 在庫
          .c-form-label = f.label :stock, '在庫数量'
          = f.number_field :stock, value: @product.stock, min: 0

          .c-form-label = f.label :comment, 'コメント'
          = f.text_area :comment, placeholder: 'コメント', value: @product.comment, rows: 5, required: :true

          .c-form-label = f.label :image, '画像'
          = f.file_field :image, accept: :image

          .u-ta-center.u-mt-30 = f.submit "更新"

app/views/products/index.html.slim
.title-heading
  h1 PRODUCTS
= render 'search_form'

= render 'product'
.pagination = will_paginate @products

app/views/products/new.html.slim
.main.products-new
  .container
    h1.form-heading
      | 出品する
    p
      | 商品情報を入力してください。
    = form_with model: @product, url: products_path, local: true do |f|
    
      .form
        .form-body
          - @product.errors.full_messages.each do |message|
            .form-error
              = message
          
          .c-form-label = f.label :name, '品名'
          = f.text_field :name, placeholder: '品名', required: :true

          .c-form-label = f.label :category, 'カテゴリー'
          = f.text_field :category, placeholder: 'カテゴリー', required: :true

          .c-form-label = f.label :price, '値段'
          = f.text_field :price, value: @product.price, required: :true
            |円

          .c-form-label = f.label :size, 'サイズ'
          = f.select :size, Product.sizes.keys, {}

          .c-form-label = f.label :stock, '在庫数量'
          = f.number_field :stock, value: 0, min: 0

          .c-form-label = f.label :comment, 'コメント'
          = f.text_area :comment, placeholder: 'コメント', rows: 5, required: :true
          
          .c-form-label = f.label :image, '画像'
           = f.file_field :image, accept: :image
          
          .u-ta-center.u-mt-30 = f.submit "出品"

app/views/products/show.html.slim
- provide :title, '商品詳細'
.p-product
  .p-product__inner
    - if @product
      = render 'products/photo'
      = render 'products/information'
    - else
      p 商品はありません